name: latestlnf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  video_player: ^2.8.5
  firebase_core: ^2.30.1
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.19.0
  firebase_auth_platform_interface: ^7.2.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.0
  cloud_firestore_platform_interface: ^6.2.0
  intl: ^0.19.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.10-nullsafety.6
  geocoding: ^3.0.0
  url_launcher: ^6.2.2
  provider: ^6.1.1
  flutter_custom_dialog: ^1.3.0
  font_awesome_flutter: ^10.6.0
  flutter_datetime_picker: ^1.5.1
  get: ^4.6.6
  camera: ^0.11.0+1
  image_picker: ^1.1.1
  image: ^3.0.1
  firebase_storage: ^11.7.5
  fluttertoast: ^8.2.5
  path_provider: ^2.1.3
  firebase_app_check: ^0.2.2+7
  http: ^0.13.6
  carousel_slider: ^4.0.0
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  tflite: ^1.1.2
  # flutter_mobile_vision_2:
  #   git:
  #     url: https://github.com/edufolly/flutter_mobile_vision.git
  #     ref: v2



  # tflite_v2: ^1.0.0
  # flutter_mobile_vision_2: ^0.1.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_lost.png"
  adaptive_icon_background: "#ffffff" # Optional, used for Android adaptive icons
  adaptive_icon_foreground: "assets/LOST.png" # Optional, used for Android adaptive icons

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/LOST.mp4
      - assets/logo_lost.png
      - assets/apple.png
      - assets/google.png
      - assets/background_image.png
      - assets/captureimage.png
      - assets/icon_image.png
      - assets/LOST.png
      - assets/labels.txt
      - assets/ad1.jpeg
      - assets/ad2.jpeg
      - assets/ad3.jpeg
      - assets/ad4.jpeg
      - assets/ad5.jpeg
      - assets/ad6.jpeg
      - assets/image.png




