// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ87we-UyaWUBXXRRxkJR56M6Aap6nvjM',
    appId: '1:224789638534:web:b2d22c81f2d941322b1007',
    messagingSenderId: '224789638534',
    projectId: 'online-database-7980b',
    authDomain: 'online-database-7980b.firebaseapp.com',
    storageBucket: 'online-database-7980b.appspot.com',
    measurementId: 'G-72EWCG5BNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPF211za73VNRq3TaUjr4_vSc1kuBPpl8',
    appId: '1:224789638534:android:471bae68b1bd7a5c2b1007',
    messagingSenderId: '224789638534',
    projectId: 'online-database-7980b',
    storageBucket: 'online-database-7980b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2UjPMsc6zluajbL74UzH8mcf8H_xwDKQ',
    appId: '1:224789638534:ios:d11a57b46b87739a2b1007',
    messagingSenderId: '224789638534',
    projectId: 'online-database-7980b',
    storageBucket: 'online-database-7980b.appspot.com',
    iosBundleId: 'com.example.latestlnf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2UjPMsc6zluajbL74UzH8mcf8H_xwDKQ',
    appId: '1:224789638534:ios:d11a57b46b87739a2b1007',
    messagingSenderId: '224789638534',
    projectId: 'online-database-7980b',
    storageBucket: 'online-database-7980b.appspot.com',
    iosBundleId: 'com.example.latestlnf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ87we-UyaWUBXXRRxkJR56M6Aap6nvjM',
    appId: '1:224789638534:web:321e74a5f5f2bb6f2b1007',
    messagingSenderId: '224789638534',
    projectId: 'online-database-7980b',
    authDomain: 'online-database-7980b.firebaseapp.com',
    storageBucket: 'online-database-7980b.appspot.com',
    measurementId: 'G-XHZSYFFHTM',
  );
}
